import {sqliteTable,text,integer,real,primaryKey,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const players=sqliteTable('players',{uid:text('uid').primaryKey(),name:text('name').notNull(),listed:integer('listed').notNull().default(0),code:text('code')},t=>[uniqueIndex('players_code').on(t.code)]);
export const finishes=sqliteTable('finishes',{id:text('id').primaryKey(),uid:text('uid').notNull(),puzzle:text('puzzle').notNull(),points:integer('points').notNull(),stars:integer('stars').notNull(),moves:integer('moves').notNull(),hints:integer('hints').notNull(),seconds:real('seconds').notNull(),day:text('day').notNull(),radiant:integer('radiant').notNull().default(0),perfect:integer('perfect').notNull().default(0),version:integer('version').notNull().default(2)},t=>[index('finishes_player').on(t.uid),index('finishes_puzzle').on(t.puzzle)]);
export const best=sqliteTable('best',{uid:text('uid').notNull(),puzzle:text('puzzle').notNull(),points:integer('points').notNull(),stars:integer('stars').notNull(),moves:integer('moves').notNull(),radiant:integer('radiant').notNull().default(0),perfect:integer('perfect').notNull().default(0)},t=>[primaryKey({columns:[t.uid,t.puzzle]})]);
export const activity=sqliteTable('activity',{uid:text('uid').notNull(),day:text('day').notNull()},t=>[primaryKey({columns:[t.uid,t.day]})]);
export const rewards=sqliteTable('rewards',{uid:text('uid').notNull(),period:text('period').notNull(),kind:text('kind').notNull(),points:integer('points').notNull(),streak:integer('streak').notNull()},t=>[primaryKey({columns:[t.uid,t.period,t.kind]})]);
export const walletEntries=sqliteTable('wallet_entries',{uid:text('uid').notNull(),reason:text('reason').notNull(),amount:integer('amount').notNull()},t=>[primaryKey({columns:[t.uid,t.reason]})]);
export const guestClaims=sqliteTable('guest_claims',{id:text('id').primaryKey(),uid:text('uid').notNull(),puzzle:text('puzzle').notNull(),day:text('day').notNull(),target:integer('target').notNull()},t=>[index('guest_claims_player').on(t.uid)]);
// Pulse runs: one row per submitted run; the board shows each player's best for the week.
export const pulseRuns=sqliteTable('pulse_runs',{id:text('id').primaryKey(),uid:text('uid').notNull(),week:integer('week').notNull(),score:integer('score').notNull(),boards:integer('boards').notNull(),turns:integer('turns').notNull(),seconds:real('seconds').notNull(),day:text('day').notNull()},t=>[index('pulse_week').on(t.week,t.score)]);
export const friends=sqliteTable('friends',{uid:text('uid').notNull(),friend:text('friend').notNull()},t=>[primaryKey({columns:[t.uid,t.friend]})]);
// Anonymous counters: no player, device or address is stored.
export const stats=sqliteTable('stats',{day:text('day').notNull(),puzzle:text('puzzle').notNull(),kind:text('kind').notNull(),n:integer('n').notNull()},t=>[primaryKey({columns:[t.day,t.puzzle,t.kind]})]);
